def loadCountryMap():
    countryMapDict = {
        '"AD"':	"EMEA",
        '"AE"':	"EMEA",
        '"AF"':	"APAC",
        '"AG"':	"North America",
        '"AL"':	"EMEA",
        '"AM"':	"APAC",
        '"AO"':	"EMEA",
        '"AQ"':	"APAC",
        '"AR"':	"South America",
        '"AS"':	"APAC",
        '"AT"':	"EMEA",
        '"AU"':	"Australia",
        '"AW"':	"North America",
        '"AZ"':	"APAC",
        '"BA"':	"EMEA",
        '"BB"':	"North America",
        '"BD"':	"APAC",
        '"BE"':	"EMEA",
        '"BF"':	"EMEA",
        '"BG"':	"EMEA",
        '"BH"':	"EMEA",
        '"BI"':	"EMEA",
        '"BJ"':	"EMEA",
        '"BM"':	"North America",
        '"BN"':	"APAC",
        '"BO"':	"South America",
        '"BR"':	"South America",
        '"BS"':	"North America",
        '"BT"':	"APAC",
        '"BV"':	"EMEA",
        '"BW"':	"EMEA",
        '"BY"':	"EMEA",
        '"BZ"':	"North America",
        '"CA"':	"North America",
        '"CC"':	"APAC",
        '"CD"':	"APAC",
        '"CF"':	"EMEA",
        '"CG"':	"EMEA",
        '"CH"':	"EMEA",
        '"CI"':	"EMEA",
        '"CK"':	"North America",
        '"CL"':	"South America",
        '"CM"':	"EMEA",
        '"CO"':	"South America",
        '"CR"':	"South America",
        '"CU"':	"North America",
        '"CV"':	"EMEA",
        '"CX"':	"APAC",
        '"CY"':	"EMEA",
        '"CZ"':	"EMEA",
        '"DE"':	"EMEA",
        '"DJ"':	"EMEA",
        '"DK"':	"EMEA",
        '"DM"':	"North America",
        '"DO"':	"North America",
        '"DZ"':	"EMEA",
        '"EC"':	"South America",
        '"EE"':	"EMEA",
        '"EG"':	"EMEA",
        '"EH"':	"EMEA",
        '"ER"':	"EMEA",
        '"ES"':	"EMEA",
        '"ET"':	"EMEA",
        '"EU"':	"EMEA",
        '"FI"':	"EMEA",
        '"FJ"':	"APAC",
        '"FK"':	"South America",
        '"FM"':	"APAC",
        '"FO"':	"EMEA",
        '"FR"':	"EMEA",
        '"GA"':	"EMEA",
        '"GB"':	"EMEA",
        '"GD"':	"North America",
        '"GE"':	"APAC",
        '"GF"':	"South America",
        '"GH"':	"EMEA",
        '"GI"':	"EMEA",
        '"GL"':	"North America",
        '"GM"':	"EMEA",
        '"GN"':	"EMEA",
        '"GP"':	"North America",
        '"GQ"':	"EMEA",
        '"GR"':	"EMEA",
        '"GS"':	"South America",
        '"GT"':	"North America",
        '"GU"':	"APAC",
        '"GW"':	"EMEA",
        '"GY"':	"South America",
        '"HK"':	"APAC",
        '"HM"':	"APAC",
        '"HN"':	"North America",
        '"HR"':	"EMEA",
        '"HT"':	"North America",
        '"HU"':	"EMEA",
        '"ID"':	"APAC",
        '"IE"':	"EMEA",
        '"IL"':	"EMEA",
        '"IN"':	"India",
        '"IO"':	"EMEA",
        '"IQ"':	"EMEA",
        '"IR"':	"EMEA",
        '"IS"':	"EMEA",
        '"IT"':	"EMEA",
        '"JM"':	"North America",
        '"JO"':	"EMEA",
        '"JP"':	"Japan",
        '"KE"':	"EMEA",
        '"KG"':	"APAC",
        '"KH"':	"APAC",
        '"KI"':	"APAC",
        '"KM"':	"EMEA",
        '"KP"':	"APAC",
        '"KR"':	"APAC",
        '"KW"':	"EMEA",
        '"KY"':	"North America",
        '"KZ"':	"APAC",
        '"LA"':	"APAC",
        '"LB"':	"EMEA",
        '"LI"':	"EMEA",
        '"LK"':	"APAC",
        '"LR"':	"EMEA",
        '"LS"':	"EMEA",
        '"LT"':	"EMEA",
        '"LU"':	"EMEA",
        '"LV"':	"EMEA",
        '"LY"':	"EMEA",
        '"MA"':	"EMEA",
        '"MC"':	"EMEA",
        '"MD"':	"EMEA",
        '"MG"':	"EMEA",
        '"MH"':	"APAC",
        '"MK"':	"EMEA",
        '"ML"':	"EMEA",
        '"MM"':	"APAC",
        '"MN"':	"APAC",
        '"MO"':	"APAC",
        '"MP"':	"APAC",
        '"MQ"':	"North America",
        '"MR"':	"EMEA",
        '"MS"':	"North America",
        '"MT"':	"EMEA",
        '"MU"':	"EMEA",
        '"MV"':	"APAC",
        '"MW"':	"EMEA",
        '"MX"':	"North America",
        '"MY"':	"APAC",
        '"MZ"':	"EMEA",
        '"NA"':	"EMEA",
        '"NC"':	"APAC",
        '"NE"':	"EMEA",
        '"NF"':	"APAC",
        '"NG"':	"EMEA",
        '"NI"':	"North America",
        '"NL"':	"EMEA",
        '"NO"':	"EMEA",
        '"NP"':	"APAC",
        '"NR"':	"APAC",
        '"NU"':	"APAC",
        '"NZ"':	"Australia",
        '"OM"':	"EMEA",
        '"PA"':	"North America",
        '"PE"':	"South America",
        '"PF"':	"APAC",
        '"PG"':	"APAC",
        '"PH"':	"APAC",
        '"PK"':	"APAC",
        '"PL"':	"EMEA",
        '"PN"':	"APAC",
        '"PR"':	"North America",
        '"PT"':	"EMEA",
        '"PW"':	"APAC",
        '"PY"':	"South America",
        '"QA"':	"EMEA",
        '"RE"':	"EMEA",
        '"RO"':	"EMEA",
        '"RU"':	"EMEA",
        '"RW"':	"EMEA",
        '"SA"':	"EMEA",
        '"SB"':	"APAC",
        '"SC"':	"EMEA",
        '"SD"':	"EMEA",
        '"SE"':	"EMEA",
        '"SG"':	"APAC",
        '"SI"':	"EMEA",
        '"SJ"':	"EMEA",
        '"SK"':	"EMEA",
        '"SL"':	"EMEA",
        '"SM"':	"EMEA",
        '"SN"':	"EMEA",
        '"SO"':	"EMEA",
        '"SR"':	"South America",
        '"SV"':	"North America",
        '"SY"':	"EMEA",
        '"SZ"':	"EMEA",
        '"TC"':	"North America",
        '"TD"':	"EMEA",
        '"TF"':	"APAC",
        '"TG"':	"EMEA",
        '"TH"':	"APAC",
        '"TJ"':	"APAC",
        '"TK"':	"APAC",
        '"TL"':	"APAC",
        '"TM"':	"APAC",
        '"TN"':	"EMEA",
        '"TO"':	"APAC",
        '"TR"':	"EMEA",
        '"TT"':	"North America",
        '"TV"':	"APAC",
        '"TW"':	"APAC",
        '"TZ"':	"EMEA",
        '"UA"':	"APAC",
        '"UG"':	"EMEA",
        '"UM"':	"APAC",
        '"US"':	"North America",
        '"UY"':	"South America",
        '"UZ"':	"APAC",
        '"VA"':	"EMEA",
        '"VC"':	"North America",
        '"VE"':	"South America",
        '"VG"':	"North America",
        '"VN"':	"APAC",
        '"VU"':	"APAC",
        '"WF"':	"APAC",
        '"WS"':	"APAC",
        '"YE"':	"EMEA",
        '"YT"':	"EMEA",
        '"ZA"':	"EMEA",
        '"ZM"':	"EMEA",
        '"ZW"':	"EMEA"
    }
    return countryMapDict
